### ISSUE TITLE
requesting thesis

### ISSUE THREAD

**Issue by wkyoun** [helipiotr/beng_thesis#1]
Thank you for the great source code for gps & ins

Would you please share the document file of your thesis?

**Comment by helipiotr** [comment]
Hi there, thank you for the interest! The thesis is available in Polish and I am not very sure whether I can include it here on Github. Most of the maths comes from this document:
http://www.ucalgary.ca/engo_webdocs/NES/01.20156.EHShin.pdf
If you are still interested in thesis, I can push it to your private repository. However, the document above is really helpful and should do just fine.

**Comment by wkyoun** [comment]
Thank you for the reply.
Would you please let me know how to run your matlab code?
And Also, it your code complete source to run GPS/INS, which means it is working correctly as expected?
(Since I am planning to study GPS/INS with your code)

Best Regards.

**Comment by helipiotr** [comment]
Hi, the filter works more or less properly using the real - life data. You have to be cautious when assigning the noise values in the Q-matrix in kalman_ins_gps (sigma - values) since they determine the filter robustness. It of course is not as effective as unscented Kalman filter, but it is more simple. To run just type sim_script in the Matlab console and you should do just fine, the script should be self-explanatory in case of any further issues, I hope all required files are included in this repository.

**Comment by wkyoun** [comment]
I would really appreciate your help.
I was able to run your code successfully.
with postpro.m file, I was able to draw the result of kalman filter,
but I could not figure out what the graph really means.

It would be better for us to understands if there are legend or explanation of graph and the variables in matlab code.

Lastly, what I would like to do is to simulate the kalman filter with **simulated data**
I uncommented the following lines in sim_script.m 

    20 %use simulated data (8-like trajectory) 
    21 %traj_gen  

It look like working properly with simulated data.


However, I would like to know  how to generate test inertial data with intent of using with analytic 2D trajectory in intertial_data.m 
 
For example, I don't know what the following lines in intertial_data.m means.
 
    38 %using the chain differentiation rule 
    39 dv_n= dD*dr_n + D*ddr_n; 

If I can find any reference related to generate test inertial data with intent of using with analytic 2D trajectory in intertial_data.m, which includes the mathmetical equations of the scripts in matlab,
that would be really helpful for me to understand.

I was able to find the math behind most of your code in referenced paper, 
but I could not find any related to generate test inertial data with intent of using with analytic 2D trajectory
Sorry for many question and requests.

Best Regards

**Comment by helipiotr** [comment]
Hi there,
I have added the description of all generated figures. Please bear in mind that you have to change the lines postpro / postpro_data at the end of the sim_script to allow it to plot proper figures.
The analytic trajectory is in inertial_data:
`10 r_n=[a*cos(b*t) c*sin(d*t) 0]'/N_test+r_n_0; %an arbitrarily chosen function`
Later on, you have to manually differentiate this equation:
`14 dr_n=[-a*b*sin(b*t) c*d*cos(d*t) 0]'/N_test;`
`15 ddr_n=[-a*b^2*cos(b*t) -c*d^2*sin(d*t) 0]'/N_test;`
This is done by hand and you have to do it for your chosen trajectory. 
The lines 38 and 39 just say that:
`dv_n = (v_n)' = (D * dr_n)'  = (D' * dr_n) + (D * dr_n' )`
D * dr_n transforms coordinate changes into the velocity, the chain differentiation rule is explained here https://en.wikipedia.org/wiki/Chain_rule .
